### ISSUE TITLE
Vagrant dev and integration testing environment. General picture

### ISSUE THREAD

**Issue by emli** [emli/gorjun#2]
![dev env](https://user-images.githubusercontent.com/5517490/33280284-c5000340-d3cb-11e7-9eb7-a61d7ec0372d.jpg)

**Comment by emli** [comment]
https://github.com/emli/gorjun/blob/dev/vagrant/Vagrantfile

**Comment by akarasulu** [comment]
This too can go into subutai-io/gorjun issues ... sorry I confused you. Just ask yourself if others can benefit from this information too from gorjun. Something you can have here for personal notes and things like that.
