### ISSUE TITLE
Integrate testing client and create test data

### ISSUE THREAD

**Issue by emli** [emli/gorjun#3]
https://github.com/marcoarthur/gorjun-perl-cli - client for gorjun written. 

https://github.com/subutai-io/gorjun/issues/141 - for this issue is for create or load data for gorjun. Let's create test data with client. In this way client also will be tested.

**Comment by akarasulu** [comment]
You should do these issues in the gorjun issues. Why separate them? You can still point to code and stuff in your forked repository.
